DROP DATABASE IF EXISTS Testing_System_Assignment_1;
CREATE DATABASE Testing_System_Assignment_1;
USE Testing_System_Assignment_1;

CREATE TABLE `Department`(
	Department_ID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
    Department_Name VARCHAR(50) NOT NULL UNIQUE KEY
);

CREATE TABLE `Position`(
	Position_ID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Position_Name ENUM('Dev','Test','Serum Master','PM')-- ENUM co can default khong?
);

CREATE TABLE `Account` (
	Account_ID SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(50) NOT NULL,
    User_Name  VARCHAR(50) NOT NULL,
    Full_Name VARCHAR(100) NOT NULL,
    Department_ID TINYINT UNSIGNED NOT NULL,
    Position_ID TINYINT UNSIGNED NOT NULL,
    Create_Date DATE
    );
    
CREATE TABLE `Group`(
	Group_ID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Group_Name VARCHAR(100) NOT NULL,
	Creator_ID SMALLINT UNSIGNED NOT NULL,
	Create_Date DATE
    );
    
CREATE TABLE `Group_Account`(
	Group_ID TINYINT AUTO_INCREMENT PRIMARY KEY,
	Account_ID SMALLINT UNSIGNED NOT NULL,
	Join_Date DATE
);

CREATE TABLE `Type_Question`(
	Type_ID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Type_Name ENUM('Essay','Multiple-Choise')
);

CREATE TABLE `Category_Question`(
	Category_ID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Category_Name VARCHAR(50) NOT NULL
);

CREATE TABLE `Question`(
	Question_ID SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Content VARCHAR(500) NOT NULL,
	Category_ID TINYINT UNSIGNED NOT NULL,
	Type_ID TINYINT UNSIGNED NOT NULL,
	Creator_ID SMALLINT UNSIGNED NOT NULL,
	Create_Date DATE
);

CREATE TABLE `Answer`(
	Answer_ID SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Content VARCHAR(500) NOT NULL,
	Question_ID SMALLINT UNSIGNED NOT NULL,
	isCorrect ENUM('TRUE','FALSE')
);


CREATE TABLE `Exam`(
	Exam_ID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `Code` VARCHAR(20) NOT NULL,
    Title VARCHAR(100) NOT NULL,
    Category_ID TINYINT UNSIGNED NOT NULL,
    Duration TIME,-- Cho nay de hoi(de Time hay Varchar thi chinh xac)
    Creator_ID SMALLINT UNSIGNED NOT NULL,
    Create_Date DATE
);

CREATE TABLE `Exam_Question`(
	Exam_ID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
    Question_ID SMALLINT UNSIGNED
);





    
    